// <auto-generated />
using CounterChangeFile.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CounterChangeFile.Migrations
{
    [DbContext(typeof(RepositoryDbContext))]
    [Migration("20181026125914_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CounterChangeFile.Models.Analysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int?>("ReposId");

                    b.HasKey("Id");

                    b.HasIndex("ReposId");

                    b.ToTable("Analysis");
                });

            modelBuilder.Entity("CounterChangeFile.Models.Files", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AnalysisId");

                    b.Property<int>("NumberOfChange");

                    b.Property<string>("RelativePath");

                    b.Property<int?>("ReposId");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("ReposId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("CounterChangeFile.Models.Repos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Path");

                    b.HasKey("Id");

                    b.ToTable("Repos");
                });

            modelBuilder.Entity("CounterChangeFile.Models.Analysis", b =>
                {
                    b.HasOne("CounterChangeFile.Models.Repos", "Repos")
                        .WithMany()
                        .HasForeignKey("ReposId");
                });

            modelBuilder.Entity("CounterChangeFile.Models.Files", b =>
                {
                    b.HasOne("CounterChangeFile.Models.Analysis", "Analysis")
                        .WithMany()
                        .HasForeignKey("AnalysisId");

                    b.HasOne("CounterChangeFile.Models.Repos", "Repos")
                        .WithMany()
                        .HasForeignKey("ReposId");
                });
#pragma warning restore 612, 618
        }
    }
}
